FROM golang:1.7

WORKDIR /go/src/github.com/pfernandom/streams

COPY main.go main.go

RUN go get github.com/streadway/amqp/...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .  
